<?php

namespace ContainerP179NRR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D_DJlN2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d.dJlN2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d.dJlN2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activation' => ['privates', '.errored..service_locator.d.dJlN2.App\\Entity\\Activation', NULL, 'Cannot autowire service ".service_locator.d.dJlN2": it needs an instance of "App\\Entity\\Activation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activation' => 'App\\Entity\\Activation',
        ]);
    }
}
