vich_uploader:
    db_driver: orm
    
    mappings:
        users_images:
            uri_prefix: /images/UserUpload
            upload_destination: '%kernel.project_dir%/public/images/UserUpload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true