vich_uploader:
    db_driver: orm
    
    mappings:
        users_images:
            uri_prefix: /images/UserUpload
            upload_destination: '%kernel.project_dir%/public/images/UserUpload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer