<?php

namespace ContainerDmuR0jG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d.dJlN2.App\Entity\Activation' shared service.
     *
     * @return \App\Entity\Activation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.d.dJlN2": it needs an instance of "App\\Entity\\Activation" but this type has been excluded in "config/services.yaml".');
    }
}
