<?php

namespace ContainerDmuR0jG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vxMQ6pO.App\Entity\Operation' shared service.
     *
     * @return \App\Entity\Operation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vxMQ6pO": it needs an instance of "App\\Entity\\Operation" but this type has been excluded in "config/services.yaml".');
    }
}
