<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Address' => [parent::class, 'Address', null],
        "\0".parent::class."\0".'CreatedAt' => [parent::class, 'CreatedAt', null],
        "\0".parent::class."\0".'Phone' => [parent::class, 'Phone', null],
        "\0".parent::class."\0".'UpdatedAt' => [parent::class, 'UpdatedAt', null],
        "\0".parent::class."\0".'dateBirth' => [parent::class, 'dateBirth', null],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'operations' => [parent::class, 'operations', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'Address' => [parent::class, 'Address', null],
        'CreatedAt' => [parent::class, 'CreatedAt', null],
        'Phone' => [parent::class, 'Phone', null],
        'UpdatedAt' => [parent::class, 'UpdatedAt', null],
        'dateBirth' => [parent::class, 'dateBirth', null],
        'documents' => [parent::class, 'documents', null],
        'email' => [parent::class, 'email', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'lastName' => [parent::class, 'lastName', null],
        'operations' => [parent::class, 'operations', null],
        'password' => [parent::class, 'password', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
