controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


user_pdf:
    path: /genpdf
    controller: App\Controller\UserController::generatePdf