<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKauo5LF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKauo5LF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKauo5LF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKauo5LF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKauo5LF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kauo5LF',
    'container.build_id' => '4e448305',
    'container.build_time' => 1718795707,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKauo5LF');
