<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9bbrex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9bbrex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW9bbrex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW9bbrex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW9bbrex\App_KernelDevDebugContainer([
    'container.build_hash' => 'W9bbrex',
    'container.build_id' => 'faa6520c',
    'container.build_time' => 1717545332,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9bbrex');
