<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5pplxYu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5pplxYu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5pplxYu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5pplxYu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5pplxYu\App_KernelDevDebugContainer([
    'container.build_hash' => '5pplxYu',
    'container.build_id' => 'fda854d2',
    'container.build_time' => 1717004450,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5pplxYu');
